// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import 'vue'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasicContainer: typeof import('./components/pedestal/BasicContainer.vue')['default']
    BasicContainerRightPanel: typeof import('./components/pedestal/BasicContainerRightPanel.vue')['default']
    BgArea: typeof import('./components/pedestal/BgArea.vue')['default']
    CanvasRules: typeof import('./components/canvasRules/index.vue')['default']
    ComLoadingError: typeof import('./components/comLoadingError/index.vue')['default']
    Commons: typeof import('./components/logicComps/commons/index.vue')['default']
    CompLoading: typeof import('./components/compLoading/index.vue')['default']
    CompMenus: typeof import('./components/leftMenu/CompMenus.vue')['default']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FlexBg: typeof import('./components/pedestal/FlexBg.vue')['default']
    GridBg: typeof import('./components/pedestal/GridBg.vue')['default']
    LeftMenu: typeof import('./components/leftMenu/index.vue')['default']
    Pedestal: typeof import('./components/pedestal/index.vue')['default']
    RightPanel: typeof import('./components/rightPanel/index.vue')['default']
    RPAttr: typeof import('./components/logicComps/commons/settings/RPAttr.vue')['default']
    RulerWrapper: typeof import('./components/sketchRuler/RulerWrapper.vue')['default']
    RulesLine: typeof import('./components/sketchRuler/RulesLine.vue')['default']
    Shape: typeof import('./components/shape/index.vue')['default']
    SketchRuler: typeof import('./components/sketchRuler/index.vue')['default']
    TextComp: typeof import('./components/logicComps/commons/TextComp/index.vue')['default']
    TextCompRightPanel: typeof import('./components/logicComps/commons/TextComp/TextCompRightPanel.vue')['default']
  }
}

export {}
