// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasicContainer: typeof import('./components/pedestal/BasicContainer.vue')['default']
    BasicContainerRightPanel: typeof import('./components/pedestal/BasicContainerRightPanel.vue')['default']
    BgArea: typeof import('./components/pedestal/BgArea.vue')['default']
    CanvasRules: typeof import('./components/canvasRules/index.vue')['default']
    FlexBg: typeof import('./components/pedestal/FlexBg.vue')['default']
    GridBg: typeof import('./components/pedestal/GridBg.vue')['default']
    Pedestal: typeof import('./components/pedestal/index.vue')['default']
    RightPanel: typeof import('./components/rightPanel/index.vue')['default']
    RulerWrapper: typeof import('./components/sketchRuler/RulerWrapper.vue')['default']
    RulesLine: typeof import('./components/sketchRuler/RulesLine.vue')['default']
    SketchRuler: typeof import('./components/sketchRuler/index.vue')['default']
  }
}

export {}
